// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr7JV7xHoa_sO7pTFWHuVAJo_7thBS3pc',
    appId: '1:341559074881:ios:5cf00d159930b1af7c66c0',
    messagingSenderId: '341559074881',
    projectId: 'smart-budget-app-hajer',
    storageBucket: 'smart-budget-app-hajer.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr7JV7xHoa_sO7pTFWHuVAJo_7thBS3pc',
    appId: '1:341559074881:ios:5cf00d159930b1af7c66c0',
    messagingSenderId: '341559074881',
    projectId: 'smart-budget-app-hajer',
    storageBucket: 'smart-budget-app-hajer.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2urytfee-HvhYuvV6FpYf61mSJyUf8Hs',
    appId: '1:341559074881:web:91cd811f4b280a747c66c0',
    messagingSenderId: '341559074881',
    projectId: 'smart-budget-app-hajer',
    authDomain: 'smart-budget-app-hajer.firebaseapp.com',
    storageBucket: 'smart-budget-app-hajer.firebasestorage.app',
    measurementId: 'G-BT3G2SD19M',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2urytfee-HvhYuvV6FpYf61mSJyUf8Hs',
    appId: '1:341559074881:web:91cd811f4b280a747c66c0',
    messagingSenderId: '341559074881',
    projectId: 'smart-budget-app-hajer',
    authDomain: 'smart-budget-app-hajer.firebaseapp.com',
    storageBucket: 'smart-budget-app-hajer.firebasestorage.app',
    measurementId: 'G-BT3G2SD19M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg11tZQ__NtcrWT3ON7NAhB2UWOv5yjQA',
    appId: '1:341559074881:android:b7d3fa98898e4eb07c66c0',
    messagingSenderId: '341559074881',
    projectId: 'smart-budget-app-hajer',
    storageBucket: 'smart-budget-app-hajer.firebasestorage.app',
  );

}